"""
detector_builder.py — generate the Geant4 detector construction.

Imported by make_geant4.py. Emits a construction.hh/.cc pair in the style of a
hand-written G4CMP detector construction: world, substrate, the generated
components stacked on the substrate, then lattices, surface properties and
border surfaces.

Boundaries are resolved per pair of touching volumes. A pair matches a specific
rule if one names both volumes; otherwise it falls back to the rule for that
pair of materials.
"""

from __future__ import annotations

import sys
from collections import OrderedDict

from shapely.strtree import STRtree


# --------------------------------------------------------------- adjacency
def find_touching(items, substrate_layer, tol_um):
    """Pairs of placed volumes that share a face.

    Three kinds. Everything meets the world on its exposed faces. Everything
    sitting on the substrate meets the substrate. Two volumes on the stack meet
    each other when their footprints touch, which after the gap snapping means
    a distance of zero.
    """
    subs = [it for it in items if it["layer"] == substrate_layer]
    stack = [it for it in items if it["layer"] != substrate_layer]

    pairs = []
    for it in items:
        pairs.append((it, None))                      # against the world

    for a in stack:
        for s in subs:
            if a["geom"].intersects(s["geom"]):
                pairs.append((a, s))

    if len(stack) > 1:
        geoms = [it["geom"] for it in stack]
        tree = STRtree(geoms)
        for i, a in enumerate(stack):
            for j in tree.query(a["geom"].buffer(tol_um)):
                if j <= i:
                    continue
                if geoms[i].distance(geoms[j]) <= tol_um:
                    pairs.append((a, stack[j]))
    return pairs


def resolve_boundary(a, b, cfg, world_material):
    """The boundary rule for one pair: a specific rule wins over a material one."""
    bnd = cfg.get("boundaries", {})
    name_a = a["name"]
    name_b = b["name"] if b is not None else "world"
    mat_a = a["material"]
    mat_b = b["material"] if b is not None else world_material

    for rule in bnd.get("specific", []):
        want = set(rule["volumes"])
        if want == {name_a, name_b}:
            return rule, "specific"

    for rule in bnd.get("defaults", []):
        if sorted(rule["materials"]) == sorted([mat_a, mat_b]):
            return rule, "material"
    return None, None


# ------------------------------------------------------------------ emission
HEADER = '''#ifndef {guard}
#define {guard}

#include "G4VUserDetectorConstruction.hh"
#include "G4VPhysicalVolume.hh"
#include "G4LogicalVolume.hh"
#include "G4Box.hh"
#include "G4PVPlacement.hh"
#include "G4NistManager.hh"
#include "G4SystemOfUnits.hh"
#include "G4ExtrudedSolid.hh"
#include "G4TwoVector.hh"
#include <vector>
#include <cmath>

#include "G4LatticeManager.hh"
#include "G4CMPSurfaceProperty.hh"
#include "G4CMPPhononElectrode.hh"
#include "G4LogicalBorderSurface.hh"
#include "G4MaterialPropertiesTable.hh"
#include "G4LatticeLogical.hh"
#include "G4LatticePhysical.hh"
#include "G4CMPLogicalBorderSurface.hh"

{component_includes}
// Generated by make_geant4.py -- do not edit by hand.
// chip {chip}: {n_components} components on {n_layers} layers.

class {cls} : public G4VUserDetectorConstruction
{{
public:
    {cls}();
    ~{cls}();


    virtual G4VPhysicalVolume *Construct();

private:

    G4VPhysicalVolume* phys_world = nullptr;
{members}}};

#endif
'''

SOURCE_HEAD = '''#include "{header}"

// Generated by make_geant4.py -- do not edit by hand.
// Lengths are micrometres unless stated. The substrate is centred on the
// origin, so its top face is at +{sub_half:.4f} um and every other layer sits
// on that face.

{cls}::{cls}()
{{}}

{cls}::~{cls}()
{{}}

G4VPhysicalVolume *{cls}::Construct()
{{

    // Materials
    G4NistManager* nist = G4NistManager::Instance();
{material_lines}
    // World
    G4Box *solid_world = new G4Box("solid_world", {wx:.4f}*um, {wy:.4f}*um, {wz:.4f}*um);
    G4LogicalVolume *logic_world = new G4LogicalVolume(solid_world, {world_var}, "logic_world");
    phys_world = new G4PVPlacement(0, G4ThreeVector(0.,0.,0.), logic_world, "phys_world", 0, false, 0, true);
'''


def var_for_material(mat):
    return "mat_" + mat.replace("-", "_").replace(".", "_")


def validate_boundaries(items, cfg, world_material, verbose=True):
    """Check the rules against the volumes that actually exist.

    A specific rule that names a volume which was never emitted would silently
    do nothing, and a second default rule for a material pair already covered
    would be quietly shadowed. Both are config mistakes worth surfacing.
    """
    known = {it["name"] for it in items} | {"world"}
    for rule in cfg.get("boundaries", {}).get("specific", []):
        missing = [v for v in rule["volumes"] if v not in known]
        if missing and verbose:
            print(f"  specific rule {rule['name']!r} names volumes that do not "
                  f"exist and will never apply: {missing}")

    seen = {}
    for rule in cfg.get("boundaries", {}).get("defaults", []):
        key = tuple(sorted(rule["materials"]))
        if key in seen and verbose:
            print(f"  two default rules for {list(key)}: {seen[key]!r} is used, "
                  f"{rule['name']!r} is shadowed")
        seen.setdefault(key, rule["name"])

    used = {it["material"] for it in items} | {world_material}
    for rule in cfg.get("boundaries", {}).get("defaults", []):
        unknown = [m for m in rule["materials"] if m not in used]
        if unknown and verbose:
            print(f"  default rule {rule['name']!r} mentions material(s) not in "
                  f"this build: {unknown}")


def write_detector(items, cfg, out_dir, substrate_layer, verbose=True):
    det = cfg.get("detector", {})
    cls = det.get("class_name", "MyDetectorConstruction")
    stem = det.get("file_stem", "construction")
    world_material = det.get("world_material", "G4_Galactic")
    tol = cfg["touch_tolerance_nm"] / 1000.0
    validate_boundaries(items, cfg, world_material, verbose)

    # ---- z placement: substrate centred on the origin, stack on its top face
    sub_items = [it for it in items if it["layer"] == substrate_layer]
    sub_half = sub_items[0]["z_half"] if sub_items else 0.0
    for it in items:
        it["z_center"] = 0.0 if it["layer"] == substrate_layer \
            else sub_half + it["z_half"]

    # ---- world size
    if det.get("world_half_size_um"):
        wx, wy, wz = det["world_half_size_um"]
    else:
        margin = det.get("world_margin_um", 500.0)
        xs = [v for it in items for v in it["geom"].bounds[0::2]]
        ys = [v for it in items for v in it["geom"].bounds[1::2]]
        zs = [abs(it["z_center"]) + it["z_half"] for it in items]
        wx = max(abs(min(xs)), abs(max(xs))) + margin
        wy = max(abs(min(ys)), abs(max(ys))) + margin
        wz = max(zs) + margin

    materials = OrderedDict()
    materials[world_material] = None
    for it in items:
        materials.setdefault(it["material"], None)

    lines = []
    for mat in materials:
        lines.append(f'    G4Material* {var_for_material(mat)} = '
                     f'nist->FindOrBuildMaterial("{mat}");')
    material_lines = "\n".join(lines) + "\n"

    body = SOURCE_HEAD.format(
        header=f"{stem}.hh", cls=cls, sub_half=sub_half,
        material_lines=material_lines, world_var=var_for_material(world_material),
        wx=wx, wy=wy, wz=wz)

    # ---- placements, grouped by layer like a hand-written file
    members = []
    by_layer = OrderedDict()
    for it in items:
        by_layer.setdefault(it["layer"], []).append(it)

    for layer, group in by_layer.items():
        label = "Substrate" if layer == substrate_layer else f"Layer {layer}"
        body += f"\n    // {label}\n"
        for it in group:
            obj = f"obj_{it['name']}"
            body += (f"    {it['class']} {obj};\n"
                     f"    phys_{it['name']} = {obj}.Construct(logic_world, "
                     f"G4ThreeVector(0., 0., {it['z_center']:.4f}*um));\n")
            members.append(f"    G4VPhysicalVolume* phys_{it['name']} = nullptr;\n")

    # ---- lattices
    lattices = cfg.get("lattices", {})
    body += "\n\n    // Lattice definitions for quasiparticle dynamics\n"
    body += "    G4LatticeManager* LM = G4LatticeManager::GetLatticeManager();\n\n"
    body += "    // Logical lattices\n"
    used = [m for m in materials if m != world_material]
    missing = [m for m in used if m not in lattices]
    if missing:
        sys.exit(f"config has no 'lattices' entry for {missing}")
    for mat in used:
        body += (f"    G4LatticeLogical* logic_{var_for_material(mat)}_lattice = "
                 f'LM->LoadLattice({var_for_material(mat)}, "{lattices[mat]["name"]}");\n')

    sc_emitted = set()
    body += "\n    // Physical lattices\n"
    for mat in used:
        sc = lattices[mat].get("superconductor")
        if not sc or mat in sc_emitted:
            continue
        sc_emitted.add(mat)
        v = var_for_material(mat)
        body += (
            f"    G4double dp_polycryElScatMFP_{v} = {sc['elScatMFP_nm']} * CLHEP::nm;"
            f"   // scattering length, depends on grain boundaries\n"
            f"    G4double dp_scDelta0_{v} = {sc['delta0_eV']} * CLHEP::eV;"
            f"   // superconductor zero temperature energy gap\n"
            f"    G4double dp_scTeff_{v} = {sc['Teff_K']} * CLHEP::kelvin;"
            f"   // effective temperature\n"
            f"    G4double dp_scDn_{v} = {sc['Dn_um2_per_ns']} * CLHEP::um*CLHEP::um / CLHEP::ns;"
            f"   // diffusion constant of normal-state electrons\n"
            f"    G4double dp_scTauQPTrap_{v} = {sc['tauQPTrap_ms']} * CLHEP::ms;"
            f"   // local trapping time constant\n")

    for it in items:
        v = var_for_material(it["material"])
        sc = lattices[it["material"]].get("superconductor")
        args = f"logic_{v}_lattice"
        if sc:
            args += (f", dp_polycryElScatMFP_{v}, dp_scDelta0_{v}, dp_scTeff_{v}, "
                     f"dp_scDn_{v}, dp_scTauQPTrap_{v}")
        body += (f"    G4LatticePhysical* lat_{it['name']} = "
                 f"new G4LatticePhysical({args});\n")

    body += "\n    // Miller orientation\n"
    for it in items:
        h, k, l = lattices[it["material"]].get("miller", [1, 0, 0])
        body += f"    lat_{it['name']}->SetMillerOrientation({h},{k},{l});\n"

    body += "\n    // Send it\n"
    for it in items:
        body += f"    LM->RegisterLattice(phys_{it['name']}, lat_{it['name']});\n"

    # ---- surface properties, one per distinct rule actually used
    pairs = find_touching(items, substrate_layer, tol)
    resolved, unmatched = [], []
    for a, b in pairs:
        rule, kind = resolve_boundary(a, b, cfg, world_material)
        if rule is None:
            unmatched.append((a["name"], b["name"] if b else "world"))
        else:
            resolved.append((a, b, rule, kind))

    if unmatched and verbose:
        print(f"  {len(unmatched)} touching pairs have no boundary rule, "
              f"e.g. {unmatched[:2]}")

    scat = cfg.get("boundaries", {}).get("scattering", {})
    used_rules = OrderedDict()
    for _, _, rule, _ in resolved:
        used_rules.setdefault(rule["name"], rule)

    body += "\n\n    // Define border scattering\n"
    body += "    const G4double GHz = 1e9 * hertz;\n\n"
    body += (f"    const std::vector<G4double> anhCoeffs = "
             f"{{{', '.join(str(v) for v in scat.get('anh_coeffs', []))}}};\n")
    body += (f"    const std::vector<G4double> diffCoeffs = "
             f"{{{', '.join(str(v) for v in scat.get('diff_coeffs', []))}}};\n")
    body += (f"    const std::vector<G4double> specCoeffs = "
             f"{{{', '.join(str(v) for v in scat.get('spec_coeffs', []))}}};\n\n")
    body += (f"    const G4double anhCutoff = {scat.get('anh_cutoff', 520.)}, "
             f"reflCutoff = {scat.get('refl_cutoff', 350.)};   // Units external\n\n")

    for name, rule in used_rules.items():
        nums = ",\n" + " " * 47
        vals = rule["params"]
        rows = [", ".join(f"{v}" for v in vals[0:4]),
                ", ".join(f"{v}" for v in vals[4:8]),
                ", ".join(f"{v}" for v in vals[8:10])]
        body += (f'    G4CMPSurfaceProperty* {name} = new G4CMPSurfaceProperty("{name}",\n'
                 f'{" " * 47}{rows[0]},\n{" " * 47}{rows[1]},\n{" " * 47}{rows[2]});\n')
    body += "\n"
    for name in used_rules:
        body += (f"    {name}->AddScatteringProperties(anhCutoff, reflCutoff, anhCoeffs,\n"
                 f"{' ' * 53}diffCoeffs, specCoeffs, GHz, GHz, GHz);\n")

    body += "\n    // The actual borders\n"
    for a, b, rule, kind in resolved:
        other = f"phys_{b['name']}" if b is not None else "phys_world"
        bname = f"border_{a['name']}_{b['name'] if b is not None else 'world'}"
        tag = "   // specific rule" if kind == "specific" else ""
        body += (f'    new G4CMPLogicalBorderSurface("{bname}", phys_{a["name"]}, '
                 f'{other}, {rule["name"]});{tag}\n')

    body += "\n\n\n    // Always return the physical world\n    return phys_world;\n}\n"

    includes = "".join(f'#include "{it["class"]}.hh"\n' for it in items)
    hdr = out_dir / f"{stem}.hh"
    src = out_dir / f"{stem}.cc"
    hdr.write_text(HEADER.format(
        guard=stem.upper() + "_HH", cls=cls, chip=items[0]["chip"],
        n_components=len(items), n_layers=len(by_layer),
        component_includes=includes, members="".join(members)))
    src.write_text(body)

    if verbose:
        print(f"detector: {len(items)} volumes, {len(resolved)} borders "
              f"({sum(1 for r in resolved if r[3] == 'specific')} from specific "
              f"rules), {len(used_rules)} surface properties")
    return [hdr, src]
